### ISSUE TITLE
Sponsors: Images have no alt text

### ISSUE THREAD

**Issue by pichfl** [ember-learn/ember-website#472] opened 2019-11-20 13:10 UTC
The data for the sponsors does not include their actual name, which in turn doesn't allow us to use that name as an alternative text for the logo images.

- [x] add company names to data
- [x] use as alt attribute in images

**Comment by sandstrom** [comment] 2019-12-03 10:07
How about skipping the `alt` attribute, it's just a logo? Or inferring an alt-text from the file-name?

**Comment by pichfl** [comment] 2019-12-03 15:25
Inferring the name from the filename is not suitable for properly naming companies. Skipping the attribute is what is happening right now, that *is* the problem here. Any non-seeing user can not identify the companies supporting Ember at all.

**Comment by sandstrom** [comment] 2019-12-03 16:50
Maybe it's okay if 1% of users (blind developers according to a recent StackOverflow poll) can't identify the sponsors?

By not translating the website to Mandarin, Arabic, Portuguese, etc. we're also leaving some developers in the dark. That's sad, but with limited resources one needs to prioritize.

**Comment by pichfl** [comment] 2019-12-03 20:17
Non-seeing does not equal blind. Search engines and other robots are in the same category. The time it takes arguing about this would be sufficient to add those names to the JSON document in question. This issue was created so work can be done when someone has 5 minutes at their disposal to write down the names and get on with it.

**Comment by sandstrom** [comment] 2019-12-05 08:08
@pichfl Good point about engines and bots. I've added a PR.

*(I'm still think many web projects adopt a dogmatic view on accessibility, that isn't based in statistics or reality. For example, most gain 100x more "inclusiveness" from a Mandarin translation than some aria tags. But I'm not saying this was the case here, I probably misjudged.)*

**Comment by pichfl** [comment] 2019-12-05 10:45
I do see your point and wholeheartedly agree. Thanks for taking the time 🙂

**Comment by mansona** [comment] 2019-12-05 12:48
Hey folks 👋 sorry I haven't been keeping track on these issues 🙈 

Any content changes like this should really go into master and then when we resync with master they will come back down to us. The issue is that the current sponsor list is out of date in the redesign branch.

I'm reopening this for now to keep track and we should make content changes like this to the master branch in future 👍

**Comment by MelSumner** [comment] 2019-12-23 17:57
The logos should have `role="presentation"` unless we don't otherwise present the company information.

**Comment by sandstrom** [comment] 2020-01-03 15:45
I'd like to re-iterate my two [earlier](https://github.com/ember-learn/ember-website/issues/472#issuecomment-562018421) [comments](https://github.com/ember-learn/ember-website/issues/472#issuecomment-561256187). 

I think this is a good example of "perfect is the enemy of good". Shipping an updated website is way more important than fulfilling some aria-requirements for the 1-2% of blind developers. If all you want is accessibility, you'd gain way more "access" by translating the docs to Spanish or Mandarin.

**Comment by pichfl** [comment] 2020-01-04 18:23
@MelSumner they are the only representation of the company name (be it visually or through their `alt=` attribute), which is why I opened this issue and why @sandstrom was kind enough to fill in alternative texts for all, 

Quick reminder for people out of the loop: `role="presentation"` would [remove semantic meaning](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_presentation_role), which is good if an image is just decoration. Using `alt=""` would do so a well.

**Comment by mansona** [comment] 2020-02-04 13:10
fixed in #545

**Closed by mansona** 2020-02-04 13:10 UTC
Labels: Website Redesign RFC, bug
