### ISSUE TITLE
[BUG] Inconsistent grid behavior in prod vs. dev

### ISSUE THREAD

**Issue by simonihmig** [ember-learn/ember-website#807] opened 2021-03-17 22:42 UTC
**Describe the bug**

The grid classes seem to be applied differently when running `ember serve` vs. what you see on emberjs.com. Observed this on the mascots page, but maybe (probably!?) others are involved as well.

**To Reproduce**
1. Force your browser into a mobile layout (e.g. Dev Tools iPhone device)
2. Go to http://localhost:4200/mascots
3. See a 2-column layout
4. Go to https://emberjs.com/mascots/
5. See a one-column layout

**Screenshots**

On emberjs.com:

![image](https://user-images.githubusercontent.com/1325249/111547273-2e268100-8779-11eb-97b6-2970d2d7c8e4.png)

On localhost:

![image](https://user-images.githubusercontent.com/1325249/111547336-4a2a2280-8779-11eb-8343-9004a3650944.png)

See the different order of CSS selectors being applied to the `ul.grid` element, especially with regards to the `--column-count` CSS var.

**Additional context**

https://github.com/ember-learn/ember-styleguide/pull/356 seems to be related /cc @nickschot

**Comment by simonihmig** [comment] 2021-03-17 22:48
Same for the ember-users page!

Emberjs.com:

![image](https://user-images.githubusercontent.com/1325249/111548539-27007280-877b-11eb-868b-7b57127b4821.png)

localhost:

![image](https://user-images.githubusercontent.com/1325249/111548562-31227100-877b-11eb-9c65-5229adb13945.png)

**Comment by mansona** [comment] 2021-03-18 22:18
This seems like a very strange bug 🙈 I has reminded me to add something that should really be added to the website for correctness sake https://github.com/ember-learn/ember-website/pull/809 and I'm wondering if this will fix the bug too 🤔 

Is it really only showing a difference in the columns if you have a trailing slash or not? 🙃

**Comment by ijlee2** [comment] 2021-03-29 07:05
Although #809 has been merged, the style issue is still present in `localhost:4200`.

**Comment by mansona** [comment] 2021-04-15 16:23
@ijlee2 can you give steps for reproduction? I only ask because the steps in the main description of this issue say that you go to `http://localhost:4200/mascots` and then `http://localhost:4200/mascots/` but now that #809 is merged those two should end up at the same route 🤔

**Comment by ijlee2** [comment] 2021-04-15 16:48
Hi, @mansona. Both URLs do end up in http://localhost:4200/mascots/.

However, locally, the app still seems to show 2 columns on mobile width. In production, https://emberjs.com/mascots/ correctly shows 1 column on mobile width.

<img width="900" alt="" src="https://user-images.githubusercontent.com/16869656/114906903-d08a6080-9e1a-11eb-83c2-2b936825d79e.png">

**Comment by nickschot** [comment] 2021-04-22 09:57
I've done some digging and am now quite certain clean-css is causing the issue in builds with css minification enabled (normally just production builds). ember-cli-preprocess-registry unfortunately relies on a very old version of clean-css which seems to have this as a known issue. I think the easiest thing we can do to fix this for now is still using a more specific selector as I did in https://github.com/ember-learn/ember-styleguide/pull/356

An existing issue on the ember-cli-preprocess-registry: https://github.com/ember-cli/ember-cli-preprocess-registry/issues/71

**Comment by ijlee2** [comment] 2021-04-22 10:03
@nickschot Using a more specific selector sounds okay with me. Thank you for taking time to investigate the issue.

**Closed** 2021-05-07 10:51 UTC
Labels: bug
